# Generated by Django 4.1.2 on 2022-10-15 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarOwner",
            fields=[
                (
                    "cd_carowner",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "sales_opportunity",
                    models.BooleanField(default=True, verbose_name="Sales Opportunity"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "cd_car",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("YE", "Yellow"), ("BL", "Blue"), ("GR", "Gray")],
                        max_length=10,
                        verbose_name="Color",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("HA", "Hatch"),
                            ("SE", "Sedan"),
                            ("CO", "Convertible"),
                        ],
                        max_length=15,
                        verbose_name="Model",
                    ),
                ),
                (
                    "cd_carowner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="car",
                        to="api.carowner",
                        verbose_name="Car Owner",
                    ),
                ),
            ],
        ),
    ]
