# Generated by Django 4.1.2 on 2022-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_carowner_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                choices=[("Yellow", "Yellow"), ("Blue", "Blue"), ("Gray", "Gray")],
                max_length=10,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(
                choices=[
                    ("Hatch", "Hatch"),
                    ("Sedan", "Sedan"),
                    ("Convertible", "Convertible"),
                ],
                max_length=15,
                verbose_name="Model",
            ),
        ),
    ]
