# Generated by Django 4.1.2 on 2022-10-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_car_color_alter_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="cd_car_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="api.carowner",
                verbose_name="Car Owner",
            ),
        ),
    ]
